#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
cp 0/alpha1.org 0/alpha1
cp 0/T.org 0/T

# non uniform initial Field 
funkySetFields -time 0 

phaseChangeHeatFoam

paraFoam -touchAll


