#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean smoothInterfaceProperties
wclean phaseChangeHeatFoam

# ----------------------------------------------------------------- end-of-file
