#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions



blockMesh 

#refresh alpha1 
cp 0/alpha1.org 0/alpha1
cp 0/T.org 0/T

# creat non-uniform internalField
#setFields > log.setFields
funkySetFields -time 0 > log.funkySetFields

#solve problem in serial
phaseChangeHeatFoam

paraFoam -touchAll

( cd validation && ./createGraphs ) 

cd ../

# ----------------------------------------------------------------- end-of-file
